---@param p TokenPalette
---@return table<string, vim.api.keyset.highlight>
local function cmp(p)
  return {
    -- menu text
    CmpItemAbbr = { fg = p.fg0 },
    CmpItemAbbrDeprecated = { fg = p.fg3, strikethrough = true },
    CmpItemAbbrMatch = { fg = p.accent, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = p.accent, bold = true },
    CmpItemMenu = { fg = p.fg2 },

    -- kind icons (matches blink.lua mapping)
    CmpItemKind = { fg = p.fg2 },
    CmpItemKindIcon = { link = 'CmpItemKind' },
    CmpItemKindText = { fg = p.fg1 },
    CmpItemKindTextIcon = { link = 'CmpItemKindText' },
    CmpItemKindMethod = { fg = p.accent },
    CmpItemKindMethodIcon = { link = 'CmpItemKindMethod' },
    CmpItemKindFunction = { fg = p.accent },
    CmpItemKindFunctionIcon = { link = 'CmpItemKindFunction' },
    CmpItemKindConstructor = { fg = p.blue },
    CmpItemKindConstructorIcon = { link = 'CmpItemKindConstructor' },
    CmpItemKindField = { fg = p.fg0 },
    CmpItemKindFieldIcon = { link = 'CmpItemKindField' },
    CmpItemKindVariable = { fg = p.fg0 },
    CmpItemKindVariableIcon = { link = 'CmpItemKindVariable' },
    CmpItemKindClass = { fg = p.blue },
    CmpItemKindClassIcon = { link = 'CmpItemKindClass' },
    CmpItemKindInterface = { fg = p.blue },
    CmpItemKindInterfaceIcon = { link = 'CmpItemKindInterface' },
    CmpItemKindModule = { fg = p.blue },
    CmpItemKindModuleIcon = { link = 'CmpItemKindModule' },
    CmpItemKindProperty = { fg = p.fg0 },
    CmpItemKindPropertyIcon = { link = 'CmpItemKindProperty' },
    CmpItemKindUnit = { fg = p.purple },
    CmpItemKindUnitIcon = { link = 'CmpItemKindUnit' },
    CmpItemKindValue = { fg = p.purple },
    CmpItemKindValueIcon = { link = 'CmpItemKindValue' },
    CmpItemKindEnum = { fg = p.blue },
    CmpItemKindEnumIcon = { link = 'CmpItemKindEnum' },
    CmpItemKindKeyword = { fg = p.accent2 },
    CmpItemKindKeywordIcon = { link = 'CmpItemKindKeyword' },
    CmpItemKindSnippet = { fg = p.green },
    CmpItemKindSnippetIcon = { link = 'CmpItemKindSnippet' },
    CmpItemKindColor = { fg = p.purple },
    CmpItemKindColorIcon = { link = 'CmpItemKindColor' },
    CmpItemKindFile = { fg = p.blue },
    CmpItemKindFileIcon = { link = 'CmpItemKindFile' },
    CmpItemKindReference = { fg = p.blue },
    CmpItemKindReferenceIcon = { link = 'CmpItemKindReference' },
    CmpItemKindFolder = { fg = p.blue },
    CmpItemKindFolderIcon = { link = 'CmpItemKindFolder' },
    CmpItemKindEnumMember = { fg = p.purple },
    CmpItemKindEnumMemberIcon = { link = 'CmpItemKindEnumMember' },
    CmpItemKindConstant = { fg = p.purple },
    CmpItemKindConstantIcon = { link = 'CmpItemKindConstant' },
    CmpItemKindStruct = { fg = p.blue },
    CmpItemKindStructIcon = { link = 'CmpItemKindStruct' },
    CmpItemKindEvent = { fg = p.accent2 },
    CmpItemKindEventIcon = { link = 'CmpItemKindEvent' },
    CmpItemKindOperator = { fg = p.fg1 },
    CmpItemKindOperatorIcon = { link = 'CmpItemKindOperator' },
    CmpItemKindTypeParameter = { fg = p.blue },
    CmpItemKindTypeParameterIcon = { link = 'CmpItemKindTypeParameter' },
  }
end

return cmp
