---@param p TokenPalette
---@return table<string, vim.api.keyset.highlight>
local function diffview(p)
  return {
    DiffviewNormal = { link = 'Normal' },
    DiffviewNonText = { link = 'NonText' },
    DiffviewCursorLine = { link = 'CursorLine' },
    DiffviewWinSeparator = { link = 'WinSeparator' },
    DiffviewSignColumn = { link = 'Normal' },
    DiffviewStatusLine = { link = 'StatusLine' },
    DiffviewStatusLineNC = { link = 'StatusLineNC' },
    DiffviewEndOfBuffer = { link = 'EndOfBuffer' },
    DiffviewFilePanelRootPath = { fg = p.fg3 },
    DiffviewFilePanelTitle = { fg = p.accent, bold = true },
    DiffviewFilePanelCounter = { fg = p.fg2 },
    DiffviewFilePanelFileName = { fg = p.fg0 },
    DiffviewFilePanelSelected = { link = 'Type' },
    DiffviewFilePanelInsertions = { fg = p.green },
    DiffviewFilePanelDeletions = { fg = p.red },
    DiffviewFilePanelConflicts = { fg = p.yellow },
    DiffviewFolderName = { fg = p.blue },
    DiffviewFolderSign = { fg = p.fg3 },
    DiffviewStatusAdded = { fg = p.green },
    DiffviewStatusUntracked = { fg = p.fg3 },
    DiffviewStatusModified = { fg = p.yellow },
    DiffviewStatusRenamed = { fg = p.purple },
    DiffviewStatusCopied = { fg = p.accent2 },
    DiffviewStatusTypeChange = { fg = p.blue },
    DiffviewStatusTypeChanged = { link = 'DiffviewStatusTypeChange' },
    DiffviewStatusUnmerged = { fg = p.accent },
    DiffviewStatusUnknown = { fg = p.red },
    DiffviewStatusDeleted = { fg = p.red },
    DiffviewStatusBroken = { fg = p.red, bold = true },
    DiffviewStatusIgnored = { fg = p.fg3 },
    DiffviewDim1 = { fg = p.fg3 },
    DiffviewPrimary = { fg = p.accent },
    DiffviewSecondary = { fg = p.accent2 },
    DiffviewHash = { fg = p.purple },
    DiffviewReference = { fg = p.accent },
    DiffviewReflogSelector = { link = 'Special' },
    DiffviewFilePanelPath = { fg = p.fg3 },
    DiffviewDiffAdd = { link = 'DiffAdd' },
    DiffviewDiffDelete = { link = 'DiffDelete' },
    DiffviewDiffChange = { link = 'DiffChange' },
    DiffviewDiffText = { link = 'DiffText' },
    DiffviewDiffAddAsDelete = { link = 'DiffDelete' },
    DiffviewDiffDeleteDim = { link = 'Comment' },
  }
end

return diffview
