---@param p TokenPalette
---@return table<string, vim.api.keyset.highlight>
local function nvimtree(p)
  return {
    NvimTreeNormal = { fg = p.fg0, bg = p.bg1 },
    NvimTreeNormalNC = { fg = p.fg0, bg = p.bg1 },
    NvimTreeWinSeparator = { fg = p.bg4, bg = p.bg1 },
    NvimTreeEndOfBuffer = { fg = p.bg1 },
    NvimTreeCursorLine = { bg = p.bg4 },
    NvimTreeRootFolder = { fg = p.accent, bold = true },
    NvimTreeFolderName = { fg = p.blue },
    NvimTreeFolderIcon = { fg = p.blue },
    NvimTreeOpenedFolderName = { fg = p.blue, bold = true },
    NvimTreeEmptyFolderName = { fg = p.fg3 },
    NvimTreeSymlinkFolderName = { fg = p.purple },
    NvimTreeFileName = { fg = p.fg0 },
    NvimTreeOpenedFile = { fg = p.fg0, bold = true },
    NvimTreeModifiedFile = { fg = p.yellow },
    NvimTreeSpecialFile = { fg = p.accent2 },
    NvimTreeSymlink = { fg = p.purple },
    NvimTreeIndentMarker = { fg = p.fg3 },
    NvimTreeImageFile = { fg = p.purple },
    NvimTreeGitDirty = { fg = p.yellow },
    NvimTreeGitStaged = { fg = p.green },
    NvimTreeGitMerge = { fg = p.accent },
    NvimTreeGitRenamed = { fg = p.purple },
    NvimTreeGitNew = { fg = p.green },
    NvimTreeGitDeleted = { fg = p.red },
    NvimTreeGitIgnored = { fg = p.fg3 },
    NvimTreeDiagnosticErrorIcon = { fg = p.red },
    NvimTreeDiagnosticWarnIcon = { fg = p.yellow },
    NvimTreeDiagnosticInfoIcon = { fg = p.blue },
    NvimTreeDiagnosticHintIcon = { fg = p.cyan },
    -- *HL variants: activated by renderer.highlight_git = 'name'
    NvimTreeGitFileDirtyHL = { fg = p.yellow },
    NvimTreeGitFileStagedHL = { fg = p.green },
    NvimTreeGitFileMergeHL = { fg = p.accent },
    NvimTreeGitFileRenamedHL = { fg = p.purple },
    NvimTreeGitFileNewHL = { fg = p.green },
    NvimTreeGitFileDeletedHL = { fg = p.red },
    NvimTreeGitFileIgnoredHL = { fg = p.fg3 },
    NvimTreeGitFolderDirtyHL = { link = 'NvimTreeGitFileDirtyHL' },
    NvimTreeGitFolderStagedHL = { link = 'NvimTreeGitFileStagedHL' },
    NvimTreeGitFolderMergeHL = { link = 'NvimTreeGitFileMergeHL' },
    NvimTreeGitFolderRenamedHL = { link = 'NvimTreeGitFileRenamedHL' },
    NvimTreeGitFolderNewHL = { link = 'NvimTreeGitFileNewHL' },
    NvimTreeGitFolderDeletedHL = { link = 'NvimTreeGitFileDeletedHL' },
    NvimTreeGitFolderIgnoredHL = { link = 'NvimTreeGitFileIgnoredHL' },
    -- *HL variants: activated by renderer.highlight_modified / highlight_opened_files = 'name'
    NvimTreeModifiedFileHL = { link = 'NvimTreeModifiedFile' },
    NvimTreeModifiedFolderHL = { link = 'NvimTreeModifiedFile' },
    NvimTreeOpenedHL = { link = 'NvimTreeOpenedFile' },
    -- *HL variants: activated by renderer.highlight_diagnostics = 'name'
    NvimTreeDiagnosticErrorFileHL = { link = 'DiagnosticError' },
    NvimTreeDiagnosticWarnFileHL = { link = 'DiagnosticWarn' },
    NvimTreeDiagnosticInfoFileHL = { link = 'DiagnosticInfo' },
    NvimTreeDiagnosticHintFileHL = { link = 'DiagnosticHint' },
    NvimTreeDiagnosticErrorFolderHL = { link = 'NvimTreeDiagnosticErrorFileHL' },
    NvimTreeDiagnosticWarnFolderHL = { link = 'NvimTreeDiagnosticWarnFileHL' },
    NvimTreeDiagnosticInfoFolderHL = { link = 'NvimTreeDiagnosticInfoFileHL' },
    NvimTreeDiagnosticHintFolderHL = { link = 'NvimTreeDiagnosticHintFileHL' },
  }
end

return nvimtree
