---@param p TokenPalette
---@return table<string, vim.api.keyset.highlight>
local function snacks(p)
  return {
    -- snacks.nvim (core window)
    SnacksNormal = { fg = p.fg0, bg = p.bg1 },
    SnacksNormalNC = { fg = p.fg0, bg = p.bg1 },
    SnacksBackdrop = { bg = p.bg0 },
    SnacksTitle = { fg = p.accent, bold = true },
    SnacksFooter = { link = 'FloatFooter' },
    SnacksFooterDesc = { fg = p.blue },
    SnacksFooterKey = { fg = p.accent2, bg = p.bg4 },
    SnacksWinBar = { fg = p.accent, bold = true },
    SnacksWinBarNC = { link = 'SnacksWinBar' },
    SnacksWinKey = { fg = p.accent },
    SnacksWinKeySep = { fg = p.fg3 },
    SnacksWinKeyDesc = { fg = p.fg0 },
    SnacksWinSeparator = { link = 'WinSeparator' },

    -- snacks.nvim (dashboard)
    SnacksDashboardNormal = { fg = p.fg0, bg = p.bg0 },
    SnacksDashboardDesc = { fg = p.fg1 },
    SnacksDashboardFile = { fg = p.accent },
    SnacksDashboardDir = { fg = p.fg3 },
    SnacksDashboardFooter = { fg = p.fg2, italic = true },
    SnacksDashboardHeader = { fg = p.accent, bold = true },
    SnacksDashboardIcon = { fg = p.blue },
    SnacksDashboardKey = { fg = p.accent2 },
    SnacksDashboardSpecial = { fg = p.accent },
    SnacksDashboardTitle = { fg = p.accent, bold = true },
    SnacksDashboardTerminal = { link = 'SnacksDashboardNormal' },

    -- snacks.nvim (notifier)
    SnacksNotifierHistory = { fg = p.fg0, bg = p.bg1 },
    SnacksNotifierHistoryTitle = { fg = p.accent, bold = true },
    SnacksNotifierHistoryDateTime = { fg = p.fg2 },
    SnacksNotifierMinimal = { link = 'NormalFloat' },
    SnacksNotifierIconTrace = { fg = p.fg3 },
    SnacksNotifierIconDebug = { fg = p.fg2 },
    SnacksNotifierIconInfo = { fg = p.blue },
    SnacksNotifierIconWarn = { fg = p.yellow },
    SnacksNotifierIconError = { fg = p.red },
    SnacksNotifierBorderTrace = { fg = p.fg3 },
    SnacksNotifierBorderDebug = { fg = p.fg2 },
    SnacksNotifierBorderInfo = { fg = p.blue },
    SnacksNotifierBorderWarn = { fg = p.yellow },
    SnacksNotifierBorderError = { fg = p.red },
    SnacksNotifierTitleTrace = { fg = p.fg3 },
    SnacksNotifierTitleDebug = { fg = p.fg2 },
    SnacksNotifierTitleInfo = { fg = p.blue },
    SnacksNotifierTitleWarn = { fg = p.yellow },
    SnacksNotifierTitleError = { fg = p.red },
    SnacksNotifierFooterTrace = { fg = p.fg3 },
    SnacksNotifierFooterDebug = { fg = p.fg2 },
    SnacksNotifierFooterInfo = { fg = p.blue },
    SnacksNotifierFooterWarn = { fg = p.yellow },
    SnacksNotifierFooterError = { fg = p.red },
    SnacksNotifierTrace = { fg = p.fg3 },
    SnacksNotifierDebug = { fg = p.fg2 },
    SnacksNotifierInfo = { fg = p.blue },
    SnacksNotifierWarn = { fg = p.yellow },
    SnacksNotifierError = { fg = p.red },

    -- snacks.nvim (diff)
    SnacksDiffAdd = { bg = p.diff_add },
    SnacksDiffAddLineNr = { fg = p.green, bg = p.diff_add },
    SnacksDiffDelete = { bg = p.diff_del },
    SnacksDiffDeleteLineNr = { fg = p.red, bg = p.diff_del },
    SnacksDiffContext = { bg = p.diff_change },
    SnacksDiffContextLineNr = { fg = p.fg2, bg = p.diff_change },
    SnacksDiffConflict = { bg = p.diff_text },
    SnacksDiffConflictLineNr = { fg = p.yellow, bg = p.diff_text },
    SnacksDiffHeader = { fg = p.accent, bold = true },
    SnacksDiffLabel = { fg = p.fg2 },
    SnacksHunkHeader = { fg = p.cyan, bg = p.diff_change },

    -- snacks.nvim (picker ui)
    SnacksPickerMatch = { fg = p.accent, bold = true },
    SnacksPickerSearch = { link = 'Search' },
    SnacksPickerPrompt = { fg = p.accent },
    SnacksPickerInputSearch = { fg = p.accent2 },
    SnacksPickerSpecial = { fg = p.accent },
    SnacksPickerLabel = { fg = p.accent },
    SnacksPickerToggle = { fg = p.blue, bg = p.bg4 },
    SnacksPickerSelected = { fg = p.accent, bold = true },
    SnacksPickerUnselected = { fg = p.fg3 },
    SnacksPickerSpinner = { fg = p.accent },
    SnacksPickerTotals = { fg = p.fg3 },
    SnacksPickerBold = { bold = true },
    SnacksPickerItalic = { italic = true },
    SnacksPickerDimmed = { fg = p.fg3 },
    SnacksPickerCode = { fg = p.green, bg = p.bg2 },
    SnacksPickerDelim = { fg = p.fg3 },
    SnacksPickerComment = { fg = p.fg2 },
    SnacksPickerDesc = { fg = p.fg2 },
    SnacksPickerIdx = { fg = p.accent2 },
    SnacksPickerRow = { fg = p.green },
    SnacksPickerCol = { fg = p.fg3 },
    SnacksPickerTree = { fg = p.fg3 },
    SnacksPickerTime = { fg = p.fg2 },
    SnacksPickerCmd = { fg = p.accent },
    SnacksPickerCmdBuiltin = { fg = p.accent2 },
    SnacksPickerRule = { fg = p.fg3 },

    -- snacks.nvim (picker window)
    SnacksPickerList = { fg = p.fg0, bg = p.bg1 },
    SnacksPickerListCursorLine = { bg = p.bg4 },
    SnacksPickerInput = { fg = p.fg0, bg = p.bg1 },
    SnacksPickerBox = { link = 'SnacksNormal' },
    SnacksPickerPreview = { fg = p.fg0, bg = p.bg0 },
    SnacksPickerPreviewCursorLine = { bg = p.bg4 },
    SnacksPickerPickWin = { link = 'Search' },
    SnacksPickerPickWinCurrent = { link = 'CurSearch' },

    -- snacks.nvim (picker files)
    SnacksPickerFile = { fg = p.fg0 },
    SnacksPickerDir = { fg = p.fg3 },
    SnacksPickerDirectory = { fg = p.blue },
    SnacksPickerPathIgnored = { fg = p.fg3 },
    SnacksPickerPathHidden = { fg = p.fg3 },
    SnacksPickerLink = { fg = p.purple },
    SnacksPickerLinkBroken = { fg = p.red },

    -- snacks.nvim (picker git)
    SnacksPickerGitCommit = { fg = p.purple },
    SnacksPickerGitBreaking = { fg = p.red, bold = true },
    SnacksPickerGitDetached = { fg = p.yellow },
    SnacksPickerGitBranch = { fg = p.accent, bold = true },
    SnacksPickerGitBranchCurrent = { fg = p.green, bold = true },
    SnacksPickerGitDate = { fg = p.fg2 },
    SnacksPickerGitIssue = { fg = p.blue },
    SnacksPickerGitAuthor = { fg = p.fg1 },
    SnacksPickerGitType = { fg = p.accent, bold = true },
    SnacksPickerGitScope = { fg = p.fg1, italic = true },
    SnacksPickerGitMsg = { fg = p.fg1 },
    SnacksPickerGitStatus = { fg = p.accent },
    SnacksPickerGitStatusAdded = { fg = p.green },
    SnacksPickerGitStatusModified = { fg = p.yellow },
    SnacksPickerGitStatusDeleted = { fg = p.red },
    SnacksPickerGitStatusRenamed = { link = 'SnacksPickerGitStatus' },
    SnacksPickerGitStatusCopied = { link = 'SnacksPickerGitStatus' },
    SnacksPickerGitStatusUntracked = { fg = p.fg3 },
    SnacksPickerGitStatusIgnored = { fg = p.fg3 },
    SnacksPickerGitStatusUnmerged = { fg = p.red },
    SnacksPickerGitStatusStaged = { fg = p.green },

    -- snacks.nvim (picker misc)
    SnacksPickerRegister = { fg = p.accent2 },
    SnacksPickerBufNr = { fg = p.fg3 },
    SnacksPickerBufFlags = { fg = p.fg3 },
    SnacksPickerBufType = { fg = p.accent },
    SnacksPickerFileType = { fg = p.green },
    SnacksPickerDiagnosticCode = { fg = p.fg2 },
    SnacksPickerDiagnosticSource = { fg = p.fg2 },
    SnacksPickerUndoAdded = { fg = p.green },
    SnacksPickerUndoRemoved = { fg = p.red },
    SnacksPickerUndoCurrent = { fg = p.accent, bold = true },
    SnacksPickerUndoSaved = { fg = p.blue },
    SnacksPickerAuEvent = { fg = p.purple },
    SnacksPickerAuPattern = { fg = p.green },
    SnacksPickerAuGroup = { fg = p.blue },
    SnacksPickerKeymapMode = { fg = p.accent2 },
    SnacksPickerKeymapLhs = { fg = p.accent },
    SnacksPickerKeymapNowait = { fg = p.purple },
    SnacksPickerKeymapRhs = { fg = p.fg3 },
    SnacksPickerManPage = { fg = p.accent },
    SnacksPickerManSection = { fg = p.accent2 },
    SnacksPickerManDesc = { fg = p.fg1 },
    SnacksPickerLspDisabled = { fg = p.yellow },
    SnacksPickerLspEnabled = { fg = p.green },
    SnacksPickerLspAttached = { fg = p.yellow },
    SnacksPickerLspAttachedBuf = { fg = p.blue },
    SnacksPickerLspUnavailable = { fg = p.red },
    SnacksPickerNotificationMessage = { fg = p.fg0 },

    -- snacks.nvim (picker icons)
    SnacksPickerIcon = { fg = p.blue },
    SnacksPickerIconArray = { fg = p.blue },
    SnacksPickerIconBoolean = { fg = p.purple },
    SnacksPickerIconCategory = { fg = p.accent2 },
    SnacksPickerIconClass = { fg = p.blue },
    SnacksPickerIconConstant = { fg = p.purple },
    SnacksPickerIconConstructor = { fg = p.blue },
    SnacksPickerIconEnum = { fg = p.blue },
    SnacksPickerIconEnumMember = { fg = p.purple },
    SnacksPickerIconEvent = { fg = p.accent2 },
    SnacksPickerIconField = { fg = p.fg0 },
    SnacksPickerIconFile = { fg = p.fg0 },
    SnacksPickerIconFunction = { fg = p.accent },
    SnacksPickerIconInterface = { fg = p.blue },
    SnacksPickerIconKey = { fg = p.fg0 },
    SnacksPickerIconMethod = { fg = p.accent },
    SnacksPickerIconModule = { fg = p.blue },
    SnacksPickerIconName = { fg = p.fg0 },
    SnacksPickerIconNamespace = { fg = p.blue },
    SnacksPickerIconNull = { fg = p.purple },
    SnacksPickerIconNumber = { fg = p.purple },
    SnacksPickerIconObject = { fg = p.blue },
    SnacksPickerIconOperator = { fg = p.fg1 },
    SnacksPickerIconPackage = { fg = p.blue },
    SnacksPickerIconProperty = { fg = p.fg0 },
    SnacksPickerIconSource = { fg = p.fg2 },
    SnacksPickerIconString = { fg = p.green },
    SnacksPickerIconStruct = { fg = p.blue },
    SnacksPickerIconTypeParameter = { fg = p.blue },
    SnacksPickerIconVariable = { fg = p.fg0 },

    -- snacks.nvim (indent)
    SnacksIndent = { fg = p.indent },
    SnacksIndent1 = { link = 'SnacksIndent' },
    SnacksIndent2 = { link = 'SnacksIndent' },
    SnacksIndent3 = { link = 'SnacksIndent' },
    SnacksIndent4 = { link = 'SnacksIndent' },
    SnacksIndent5 = { link = 'SnacksIndent' },
    SnacksIndent6 = { link = 'SnacksIndent' },
    SnacksIndent7 = { link = 'SnacksIndent' },
    SnacksIndent8 = { link = 'SnacksIndent' },
    SnacksIndentBlank = { fg = p.indent },
    SnacksIndentScope = { fg = p.indent_active },
    SnacksIndentChunk = { fg = p.indent_active },

    -- snacks.nvim (input)
    SnacksInputNormal = { fg = p.fg0, bg = p.bg1 },
    SnacksInputIcon = { fg = p.accent },
    SnacksInputBorder = { fg = p.blue, bg = p.bg1 },
    SnacksInputTitle = { fg = p.blue, bold = true },
    SnacksInputPrompt = { link = 'SnacksInputTitle' },

    -- snacks.nvim (github)
    SnacksGhGreen = { fg = p.green },
    SnacksGhPurple = { fg = p.purple },
    SnacksGhGray = { fg = p.fg2 },
    SnacksGhRed = { fg = p.red },
    SnacksGhNumber = { fg = p.accent2 },
    SnacksGhBranch = { fg = p.accent },
    SnacksGhLabel = { fg = p.blue },
    SnacksGhDelim = { fg = p.fg3 },
    SnacksGhStat = { fg = p.fg2 },
    SnacksGhBotBadge = { fg = p.fg3 },
    SnacksGhScratchTitle = { fg = p.accent2 },
    SnacksGhScratchBorder = { fg = p.accent2 },
    SnacksGhNormal = { fg = p.fg0, bg = p.bg1 },
    SnacksGhNormalFloat = { link = 'NormalFloat' },
    SnacksGhBorder = { link = 'FloatBorder' },
    SnacksGhTitle = { fg = p.accent, bold = true },
    SnacksGhFooter = { fg = p.fg2 },
    SnacksGhAdditions = { fg = p.green },
    SnacksGhDeletions = { fg = p.red },
    SnacksGhAssocBadge = { fg = p.blue },
    SnacksGhAuthorBadge = { fg = p.accent },
    SnacksGhOwnerBadge = { fg = p.accent2 },
    SnacksGhReactionBadge = { fg = p.purple },
    SnacksGhSuggestionBadge = { link = 'SnacksGhGreen' },
    SnacksGhStatBadge = { fg = p.fg2 },
    SnacksGhUserBadge = { fg = p.blue },
    SnacksGhCommentAction = { fg = p.accent },
    SnacksGhCheckFailure = { fg = p.red },
    SnacksGhCheckPending = { fg = p.yellow },
    SnacksGhCheckSkipped = { fg = p.fg3 },
    SnacksGhCheckSuccess = { fg = p.green },
    SnacksGhIssueCompleted = { fg = p.purple },
    SnacksGhIssueOpen = { fg = p.green },
    SnacksGhIssueOther = { fg = p.fg2 },
    SnacksGhPrBlocked = { fg = p.red },
    SnacksGhPrClean = { fg = p.green },
    SnacksGhPrClosed = { fg = p.red },
    SnacksGhPrDirty = { fg = p.yellow },
    SnacksGhPrDraft = { fg = p.fg3 },
    SnacksGhPrMerged = { fg = p.purple },
    SnacksGhPrOpen = { fg = p.green },
    SnacksGhPrUnstable = { fg = p.yellow },
    SnacksGhReviewApproved = { fg = p.green },
    SnacksGhReviewChangesRequested = { fg = p.red },
    SnacksGhReviewCommented = { fg = p.blue },
    SnacksGhReviewPending = { fg = p.yellow },
    SnacksGhDiffAdd = { link = 'SnacksDiffAdd' },
    SnacksGhDiffAddLineNr = { link = 'SnacksDiffAddLineNr' },
    SnacksGhDiffDelete = { link = 'SnacksDiffDelete' },
    SnacksGhDiffDeleteLineNr = { link = 'SnacksDiffDeleteLineNr' },
    SnacksGhDiffContext = { link = 'SnacksDiffContext' },
    SnacksGhDiffContextLineNr = { link = 'SnacksDiffContextLineNr' },
    SnacksGhDiffHeader = { link = 'SnacksDiffHeader' },

    -- snacks.nvim (profiler)
    SnacksProfilerIcon = { link = 'SnacksProfilerIconInfo' },
    SnacksProfilerBadge = { link = 'SnacksProfilerBadgeInfo' },
    SnacksProfilerIconTrace = { link = 'SnacksProfilerIconInfo' },
    SnacksProfilerBadgeTrace = { link = 'SnacksProfilerBadgeInfo' },
    SnacksProfilerIconInfo = { link = 'DiagnosticVirtualTextInfo' },
    SnacksProfilerBadgeInfo = { link = 'DiagnosticVirtualTextInfo' },
    SnacksProfilerIconWarn = { link = 'DiagnosticVirtualTextWarn' },
    SnacksProfilerBadgeWarn = { link = 'DiagnosticVirtualTextWarn' },
    SnacksProfilerIconError = { link = 'DiagnosticVirtualTextError' },
    SnacksProfilerBadgeError = { link = 'DiagnosticVirtualTextError' },
    SnacksProfilerHot01 = { bg = p.bg4 },
    SnacksProfilerHot02 = { bg = p.bg4 },
    SnacksProfilerHot03 = { bg = p.bg4 },
    SnacksProfilerHot04 = { bg = p.bg4 },
    SnacksProfilerHot05 = { bg = p.bg5 },
    SnacksProfilerHot06 = { bg = p.bg5 },
    SnacksProfilerHot07 = { bg = p.bg5 },
    SnacksProfilerHot08 = { bg = p.bg5 },
    SnacksProfilerHot09 = { bg = p.diff_del },
    SnacksProfilerHot10 = { bg = p.diff_del },
    SnacksProfilerHot11 = { bg = p.diff_del },
    SnacksProfilerHot12 = { bg = p.diff_del },
    SnacksProfilerHot13 = { bg = p.diff_del_inline },
    SnacksProfilerHot14 = { bg = p.diff_del_inline },
    SnacksProfilerHot15 = { bg = p.diff_del_inline },
    SnacksProfilerHot16 = { bg = p.diff_del_inline },
    SnacksProfilerHot17 = { bg = p.diff_del_strong },
    SnacksProfilerHot18 = { bg = p.diff_del_strong },
    SnacksProfilerHot19 = { bg = p.diff_del_strong },
    SnacksProfilerHot20 = { bg = p.diff_del_strong },

    -- snacks.nvim (dim, debug, scratch, statuscolumn, zen, image)
    SnacksDim = { fg = p.fg3 },
    SnacksDebugIndent = { fg = p.fg3 },
    SnacksDebugPrint = { fg = p.fg3 },
    SnacksScratchTitle = { link = 'FloatTitle' },
    SnacksStatusColumnMark = { fg = p.accent },
    SnacksZenIcon = { fg = p.yellow },
    SnacksImageSpinner = { fg = p.accent },
    SnacksImageLoading = { fg = p.fg3 },
    SnacksImageAnchor = { fg = p.accent },
    SnacksImageMath = { fg = p.purple },
  }
end

return snacks
