---@param p TokenPalette
---@return table<string, vim.api.keyset.highlight>
local function temper(p)
  local groups = {
    Comment = { fg = p.fg2, italic = true },
    Constant = { fg = p.accent, italic = true },
    String = { fg = p.accent, italic = true },
    Character = { fg = p.accent, italic = true },
    Number = { fg = p.accent, italic = true },
    Boolean = { fg = p.accent, italic = true },
    Float = { fg = p.accent, italic = true },
    Identifier = { fg = p.fg0 },
    Function = { fg = p.accent, bold = true },
    Statement = { fg = p.accent2 },
    Conditional = { fg = p.accent2 },
    Repeat = { fg = p.accent2 },
    Label = { fg = p.accent2 },
    Operator = { fg = p.fg1 },
    Keyword = { fg = p.accent2 },
    Exception = { fg = p.accent2 },
    PreProc = { fg = p.accent2 },
    Include = { fg = p.accent2 },
    Define = { fg = p.accent2 },
    Macro = { fg = p.accent2 },
    PreCondit = { fg = p.accent2 },
    Type = { fg = p.fg1, italic = true },
    StorageClass = { fg = p.fg1, italic = true },
    Structure = { fg = p.fg1, italic = true },
    Typedef = { fg = p.fg1, italic = true },
    Special = { fg = p.purple, italic = true },
    SpecialChar = { fg = p.purple, italic = true },
    Tag = { fg = p.fg1 },
    Delimiter = { fg = p.fg1 },
    SpecialComment = { fg = p.fg2, italic = true },
  }

  local overrides = {
    ['@variable'] = { fg = p.fg0 },
    ['@variable.builtin'] = { fg = p.fg1, italic = true },
    ['@variable.parameter'] = { fg = p.fg1 },
    ['@variable.parameter.builtin'] = { fg = p.fg1, italic = true },
    ['@variable.member'] = { fg = p.fg0 },
    ['@constant'] = { fg = p.accent, italic = true },
    ['@constant.builtin'] = { fg = p.accent, italic = true },
    ['@constant.macro'] = { fg = p.accent2 },
    ['@module'] = { fg = p.fg1, italic = true },
    ['@module.builtin'] = { fg = p.fg1, italic = true },
    ['@string'] = { fg = p.accent, italic = true },
    ['@string.documentation'] = { fg = p.accent, italic = true },
    ['@string.regexp'] = { fg = p.accent, italic = true },
    ['@string.escape'] = { fg = p.accent, italic = true },
    ['@string.special'] = { fg = p.accent, italic = true },
    ['@string.special.symbol'] = { fg = p.accent, italic = true },
    ['@string.special.path'] = { fg = p.accent, italic = true },
    ['@string.special.url'] = { fg = p.accent, italic = true, underline = true },
    ['@character'] = { fg = p.accent, italic = true },
    ['@character.special'] = { fg = p.accent, italic = true },
    ['@boolean'] = { fg = p.accent, italic = true },
    ['@number'] = { fg = p.accent, italic = true },
    ['@number.float'] = { fg = p.accent, italic = true },
    ['@type'] = { fg = p.fg1, italic = true },
    ['@type.builtin'] = { fg = p.fg1, italic = true },
    ['@type.definition'] = { fg = p.accent, bold = true },
    ['@attribute'] = { fg = p.fg1, italic = true },
    ['@attribute.builtin'] = { fg = p.fg1, italic = true },
    ['@property'] = { fg = p.fg0 },
    ['@function'] = { fg = p.accent, bold = true },
    ['@function.builtin'] = { fg = p.fg1, italic = true },
    ['@function.call'] = { fg = p.accent },
    ['@function.macro'] = { fg = p.accent2 },
    ['@function.method'] = { fg = p.accent, bold = true },
    ['@function.method.call'] = { fg = p.accent },
    ['@constructor'] = { fg = p.fg1, italic = true },
    ['@operator'] = { fg = p.fg1 },
    ['@punctuation'] = { fg = p.fg1 },
    ['@punctuation.delimiter'] = { fg = p.fg1 },
    ['@punctuation.bracket'] = { fg = p.fg1 },
    ['@punctuation.special'] = { fg = p.fg1 },
    ['@comment'] = { fg = p.fg2, italic = true },
    ['@comment.documentation'] = { fg = p.fg2, italic = true },
    ['@comment.error'] = { fg = p.red, italic = true },
    ['@comment.warning'] = { fg = p.yellow, italic = true },
    ['@comment.todo'] = { fg = p.yellow, italic = true },
    ['@comment.note'] = { fg = p.fg1, italic = true },
    ['@keyword'] = { fg = p.accent2 },
    ['@keyword.coroutine'] = { fg = p.accent2 },
    ['@keyword.function'] = { fg = p.accent2 },
    ['@keyword.operator'] = { fg = p.accent2 },
    ['@keyword.import'] = { fg = p.accent2 },
    ['@keyword.type'] = { fg = p.accent2 },
    ['@keyword.modifier'] = { fg = p.accent2 },
    ['@keyword.repeat'] = { fg = p.accent2 },
    ['@keyword.return'] = { fg = p.accent2 },
    ['@keyword.debug'] = { fg = p.accent2 },
    ['@keyword.exception'] = { fg = p.accent2 },
    ['@keyword.conditional'] = { fg = p.accent2 },
    ['@keyword.conditional.ternary'] = { fg = p.accent2 },
    ['@keyword.directive'] = { fg = p.accent2 },
    ['@keyword.directive.define'] = { fg = p.accent2 },
    ['@tag'] = { fg = p.fg1 },
    ['@tag.builtin'] = { fg = p.fg1, italic = true },
    ['@tag.attribute'] = { fg = p.fg0 },
    ['@tag.delimiter'] = { fg = p.fg2 },
    ['@markup.heading'] = { fg = p.accent, bold = true },
    ['@markup.heading.1'] = { fg = p.accent, bold = true },
    ['@markup.heading.2'] = { fg = p.accent2, bold = true },
    ['@markup.heading.3'] = { fg = p.fg1, bold = true },
    ['@markup.heading.4'] = { fg = p.accent, bold = true },
    ['@markup.heading.5'] = { fg = p.accent2, bold = true },
    ['@markup.heading.6'] = { fg = p.fg1, bold = true },
    ['@markup.quote'] = { fg = p.fg2, italic = true },
    ['@markup.math'] = { fg = p.fg1, italic = true },
    ['@markup.environment'] = { fg = p.fg1 },
    ['@markup.link'] = { fg = p.accent, underline = true },
    ['@markup.link.label'] = { fg = p.accent, underline = true },
    ['@markup.link.url'] = { fg = p.accent, underline = true },
    ['@markup.raw'] = { fg = p.accent, italic = true },
    ['@markup.raw.block'] = { fg = p.accent, italic = true },
    ['@markup.list'] = { fg = p.accent2 },
    ['@lsp.type.class'] = { link = '@type' },
    ['@lsp.type.decorator'] = { link = '@attribute' },
    ['@lsp.type.enum'] = { link = '@type' },
    ['@lsp.type.enumMember'] = { link = '@constant' },
    ['@lsp.type.event'] = { link = '@type' },
    ['@lsp.type.function'] = { link = '@function.call' },
    ['@lsp.type.interface'] = { link = '@type' },
    ['@lsp.type.macro'] = { link = '@function.macro' },
    ['@lsp.type.method'] = { link = '@function.method.call' },
    ['@lsp.type.namespace'] = { link = '@module' },
    ['@lsp.type.struct'] = { link = '@type' },
    ['@lsp.type.type'] = { link = '@type' },
    ['@lsp.type.typeParameter'] = { link = '@type' },
  }

  for _, token_type in ipairs({
    'class',
    'enum',
    'function',
    'interface',
    'method',
    'struct',
    'type',
    'typeParameter',
  }) do
    for _, modifier in ipairs({ 'declaration', 'definition' }) do
      overrides['@lsp.typemod.' .. token_type .. '.' .. modifier] = { fg = p.accent, bold = true }
    end
  end

  for name, value in pairs(overrides) do
    groups[name] = value
  end

  for level, color in ipairs({ p.accent, p.accent2, p.fg1, p.accent, p.accent2, p.fg1 }) do
    groups['RenderMarkdownH' .. level] = { fg = color, bold = true }
    groups['RenderMarkdownH' .. level .. 'Bg'] = { fg = color, bg = p.bg4, bold = true }
    groups['MarkviewHeading' .. level] = { fg = color, bg = p.bg4, bold = true }
    groups['MarkviewHeading' .. level .. 'Sign'] = { fg = color, bold = true }
  end

  return groups
end

return temper
