# Generated by token colorscheme. Do not edit manually.
# Source this file from config.fish to append token colors to FZF_DEFAULT_OPTS.

set -gx FZF_DEFAULT_OPTS (string join " " -- \
  $FZF_DEFAULT_OPTS \
  --border \
  '--color=fg:#C3C8CC,bg:#272C33,hl:#5CC1B3' \
  '--color=fg+:#C3C8CC,bg+:#3A414A,hl+:#5CC1B3' \
  '--color=border:#858F9B,header:#51B8AA,gutter:#272C33' \
  '--color=spinner:#E7CDFF,info:#9AA4AE' \
  '--color=pointer:#5CC1B3,marker:#5EC4B5,prompt:#5CC1B3')
