# Generated by token colorscheme. Do not edit manually.
# Source this file from config.fish to append token colors to FZF_DEFAULT_OPTS.

set -gx FZF_DEFAULT_OPTS (string join " " -- \
  $FZF_DEFAULT_OPTS \
  --border \
  '--color=fg:#2a2920,bg:#faf9f5,hl:#974c30' \
  '--color=fg+:#2a2920,bg+:#dddcd6,hl+:#974c30' \
  '--color=border:#858179,header:#3e6b95,gutter:#faf9f5' \
  '--color=spinner:#8b602e,info:#6c675f' \
  '--color=pointer:#974c30,marker:#356831,prompt:#974c30')
