# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to append token colors to FZF_DEFAULT_OPTS.

export _FZF_THEME_OPTS="\
--border \
--color=fg:#28323a,bg:#fbf9f4,hl:#0048b3 \
--color=fg+:#28323a,bg+:#dedbd3,hl+:#0048b3 \
--color=border:#43505c,header:#0048b3,gutter:#fbf9f4 \
--color=spinner:#843900,info:#524b42 \
--color=pointer:#0048b3,marker:#005f2f,prompt:#0048b3
"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+${FZF_DEFAULT_OPTS} }${_FZF_THEME_OPTS}"
