# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to append token colors to FZF_DEFAULT_OPTS.

export _FZF_THEME_OPTS="\
--border \
--color=fg:#DCE1E6,bg:#272C33,hl:#56BCAE \
--color=fg+:#DCE1E6,bg+:#3A414A,hl+:#56BCAE \
--color=border:#626C77,header:#56BCAE,gutter:#272C33 \
--color=spinner:#B184D5,info:#929BA5 \
--color=pointer:#56BCAE,marker:#56BCAE,prompt:#56BCAE
"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+${FZF_DEFAULT_OPTS} }${_FZF_THEME_OPTS}"
