# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to append token colors to FZF_DEFAULT_OPTS.

export _FZF_THEME_OPTS="\
--border \
--color=fg:#283039,bg:#F5F7F8,hl:#005850 \
--color=fg+:#283039,bg+:#DCE2E7,hl+:#005850 \
--color=border:#444E59,header:#005850,gutter:#F5F7F8 \
--color=spinner:#683495,info:#414C57 \
--color=pointer:#005850,marker:#005B53,prompt:#005850
"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+${FZF_DEFAULT_OPTS} }${_FZF_THEME_OPTS}"
