# Generated by token colorscheme. Do not edit manually.
# Source this file from config.fish to append token colors to FZF_DEFAULT_OPTS.

set -gx FZF_DEFAULT_OPTS (string join " " -- \
  $FZF_DEFAULT_OPTS \
  --border \
  '--color=fg:#292a24,bg:#fbf9f4,hl:#a44e31' \
  '--color=fg+:#292a24,bg+:#dedbd3,hl+:#a44e31' \
  '--color=border:#888177,header:#536f88,gutter:#fbf9f4' \
  '--color=spinner:#846128,info:#6d675f' \
  '--color=pointer:#a44e31,marker:#4f714b,prompt:#a44e31')
