# Generated by token colorscheme. Do not edit manually.
# Source this file from config.fish to append token colors to FZF_DEFAULT_OPTS.

set -gx FZF_DEFAULT_OPTS (string join " " -- \
  $FZF_DEFAULT_OPTS \
  --border \
  '--color=fg:#283039,bg:#F5F7F8,hl:#902A03' \
  '--color=fg+:#283039,bg+:#DCE2E7,hl+:#902A03' \
  '--color=border:#444E59,header:#035378,gutter:#F5F7F8' \
  '--color=spinner:#6b4600,info:#414C57' \
  '--color=pointer:#902A03,marker:#3D5902,prompt:#902A03')
