# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to append token colors to FZF_DEFAULT_OPTS.

export _FZF_THEME_OPTS="\
--border \
--color=fg:#292a24,bg:#fbf9f4,hl:#a44e31 \
--color=fg+:#292a24,bg+:#dedbd3,hl+:#a44e31 \
--color=border:#888177,header:#536f88,gutter:#fbf9f4 \
--color=spinner:#87601b,info:#6d675f \
--color=pointer:#a44e31,marker:#4f714b,prompt:#a44e31
"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+${FZF_DEFAULT_OPTS} }${_FZF_THEME_OPTS}"
