# Generated by token colorscheme. Do not edit manually.
# Source this file from config.fish to append token colors to FZF_DEFAULT_OPTS.

set -gx FZF_DEFAULT_OPTS (string join " " -- \
  $FZF_DEFAULT_OPTS \
  --border \
  '--color=fg:#28313A,bg:#F5F7F8,hl:#B64E2E' \
  '--color=fg+:#28313A,bg+:#DCE2E7,hl+:#B64E2E' \
  '--color=border:#828E9A,header:#34779D,gutter:#F5F7F8' \
  '--color=spinner:#946409,info:#65717D' \
  '--color=pointer:#B64E2E,marker:#5A772B,prompt:#B64E2E')
