# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to append token colors to FZF_DEFAULT_OPTS.

export _FZF_THEME_OPTS="\
--border \
--color=fg:#28313A,bg:#F5F7F8,hl:#007D72 \
--color=fg+:#28313A,bg+:#DCE2E7,hl+:#007D72 \
--color=border:#828E9A,header:#007D72,gutter:#F5F7F8 \
--color=spinner:#7845A7,info:#65717D \
--color=pointer:#007D72,marker:#007D72,prompt:#007D72
"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+${FZF_DEFAULT_OPTS} }${_FZF_THEME_OPTS}"
