# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to append token colors to FZF_DEFAULT_OPTS.

export _FZF_THEME_OPTS="\
--border \
--color=fg:#C3C8CC,bg:#272C33,hl:#EB9E83 \
--color=fg+:#C3C8CC,bg+:#3A414A,hl+:#EB9E83 \
--color=border:#858F9B,header:#88ACC4,gutter:#272C33 \
--color=spinner:#F8D28A,info:#9AA4AE \
--color=pointer:#EB9E83,marker:#A9B98C,prompt:#EB9E83
"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+${FZF_DEFAULT_OPTS} }${_FZF_THEME_OPTS}"
