# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to append token colors to FZF_DEFAULT_OPTS.

export _FZF_THEME_OPTS="\
--border \
--color=fg:#DCE1E6,bg:#272C33,hl:#B7A0E0 \
--color=fg+:#DCE1E6,bg+:#3A414A,hl+:#B7A0E0 \
--color=border:#626C77,header:#82AAD0,gutter:#272C33 \
--color=spinner:#73B7B0,info:#929BA5 \
--color=pointer:#B7A0E0,marker:#8FB583,prompt:#B7A0E0
"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+${FZF_DEFAULT_OPTS} }${_FZF_THEME_OPTS}"
