# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to append token colors to FZF_DEFAULT_OPTS.

export _FZF_THEME_OPTS="\
--border \
--color=fg:#e7e2d9,bg:#272724,hl:#d98262 \
--color=fg+:#e7e2d9,bg+:#3c3b36,hl+:#d98262 \
--color=border:#65615c,header:#829db2,gutter:#272724 \
--color=spinner:#c79b5b,info:#979189 \
--color=pointer:#d98262,marker:#86a17a,prompt:#d98262
"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+${FZF_DEFAULT_OPTS} }${_FZF_THEME_OPTS}"
