# Generated by token colorscheme. Do not edit manually.
# Source this file from config.fish to append token colors to FZF_DEFAULT_OPTS.

set -gx FZF_DEFAULT_OPTS (string join " " -- \
  $FZF_DEFAULT_OPTS \
  --border \
  '--color=fg:#c5c1b8,bg:#272724,hl:#ed9574' \
  '--color=fg+:#c5c1b8,bg+:#3c3b36,hl+:#ed9574' \
  '--color=border:#8d8983,header:#8aa5bb,gutter:#272724' \
  '--color=spinner:#f7c988,info:#a39d94' \
  '--color=pointer:#ed9574,marker:#9ab58e,prompt:#ed9574')
