# Generated by token colorscheme. Do not edit manually.
# Source this file from config.fish to append token colors to FZF_DEFAULT_OPTS.

set -gx FZF_DEFAULT_OPTS (string join " " -- \
  $FZF_DEFAULT_OPTS \
  --border \
  '--color=fg:#c3c0b8,bg:#262624,hl:#f4906f' \
  '--color=fg+:#c3c0b8,bg+:#3a3a37,hl+:#f4906f' \
  '--color=border:#8a8884,header:#81a5c4,gutter:#262624' \
  '--color=spinner:#f7c699,info:#a19c94' \
  '--color=pointer:#f4906f,marker:#8fb78c,prompt:#f4906f')
