# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to append token colors to FZF_DEFAULT_OPTS.

export _FZF_THEME_OPTS="\
--border \
--color=fg:#c9c0b1,bg:#272724,hl:#e89a49 \
--color=fg+:#c9c0b1,bg+:#3c3b36,hl+:#e89a49 \
--color=border:#91887d,header:#66abc6,gutter:#272724 \
--color=spinner:#f8c88f,info:#a69c91 \
--color=pointer:#e89a49,marker:#8cbb62,prompt:#e89a49
"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+${FZF_DEFAULT_OPTS} }${_FZF_THEME_OPTS}"
