# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to append token colors to FZF_DEFAULT_OPTS.

export _FZF_THEME_OPTS="\
--border \
--color=fg:#DCE1E6,bg:#272C33,hl:#D58A6F \
--color=fg+:#DCE1E6,bg+:#3A414A,hl+:#D58A6F \
--color=border:#626C77,header:#7FA2BA,gutter:#272C33 \
--color=spinner:#C6A15A,info:#929BA5 \
--color=pointer:#D58A6F,marker:#94A477,prompt:#D58A6F
"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+${FZF_DEFAULT_OPTS} }${_FZF_THEME_OPTS}"
