# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token-ultra dark colors.

# ZLE selection and pasted text
zle_highlight=(${zle_highlight:#region:*})
zle_highlight=(${zle_highlight:#paste:*} "region:fg=#e7e2d9,bg=#3c3b36" "paste:fg=#e7e2d9,bg=#3c3b36")

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#cf7778'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#c79b5b'
FAST_HIGHLIGHT_STYLES[alias]='fg=#829db2'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#829db2'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#829db2'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#829db2'
FAST_HIGHLIGHT_STYLES[function]='fg=#d98262'
FAST_HIGHLIGHT_STYLES[command]='fg=#829db2'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#c79b5b'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#c79b5b'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#979189'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#829db2'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#d4cfc6,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#d4cfc6,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#979189,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#d4cfc6,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#d4cfc6,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#979189'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#86a17a'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#86a17a'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#86a17a'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#cf7778,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#cf7778,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#cf7778,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[assign]='fg=#e7e2d9'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#86a17a'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[comment]='fg=#979189,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#d4cfc6'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#d4cfc6'
FAST_HIGHLIGHT_STYLES[variable]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#e7e2d9'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#c79b5b'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#979189'
FAST_HIGHLIGHT_STYLES[exec-descriptor]='fg=#c79b5b'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#c79b5b'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#829db2'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#cf7778'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#86a17a'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#c79b5b'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#829db2'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#829db2'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#86a17a'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#c79b5b'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#6ba8a8'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#829db2'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#829db2'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#c79b5b'
FAST_HIGHLIGHT_STYLES[optarg-string]='fg=#86a17a'
FAST_HIGHLIGHT_STYLES[optarg-number]='fg=#a68bbf'
FAST_HIGHLIGHT_STYLES[recursive-base]='none'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#829db2'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#cf7778'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#86a17a'
FAST_HIGHLIGHT_STYLES[subtle-bg]='bg=#4d4231'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#585855'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;130;157;178:ln=38;2;166;139;191:or=38;2;207;119;120:mi=9;38;2;207;119;120:so=38;2;134;161;122:pi=38;2;199;163;91:ex=38;2;217;130;98:bd=38;2;107;168;168:cd=38;2;107;168;168:su=1;38;2;207;119;120:sg=1;38;2;199;163;91:tw=1;38;2;134;161;122:ow=4;38;2;130;157;178:st=1;38;2;130;157;178'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;60;59;54;38;2;231;226;217"
zstyle ':completion:*:descriptions' format '%F{#979189}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#979189}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#cf7778}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#e7e2d9,bg:#272724,hl:#d98262' \
  '--color=fg+:#e7e2d9,bg+:#3c3b36,hl+:#d98262' \
  '--color=border:#65615c,header:#829db2,gutter:#272724' \
  '--color=spinner:#c79b5b,info:#979189' \
  '--color=pointer:#d98262,marker:#86a17a,prompt:#d98262'
zstyle ':fzf-tab:*' default-color $'\033[38;2;231;226;217m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;130;157;178m' $'\033[38;2;134;161;122m' $'\033[38;2;199;155;91m' $'\033[38;2;166;139;191m' $'\033[38;2;107;168;168m' $'\033[38;2;217;130;98m' $'\033[38;2;199;163;91m' $'\033[38;2;207;119;120m'

# Prompt helpers
export TOKEN_FG='#e7e2d9'
export TOKEN_BG='#272724'
export TOKEN_ACCENT='#d98262'
export TOKEN_ACCENT2='#c79b5b'
export TOKEN_BLUE='#829db2'
export TOKEN_GREEN='#86a17a'
export TOKEN_RED='#cf7778'
export TOKEN_YELLOW='#c7a35b'
export TOKEN_PURPLE='#a68bbf'
export TOKEN_CYAN='#6ba8a8'
export TOKEN_MUTED='#979189'
