# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token-temper dark colors.

# ZLE selection and pasted text
zle_highlight=(${zle_highlight:#region:*})
zle_highlight=(${zle_highlight:#paste:*} "region:fg=#C3C8CC,bg=#3A414A" "paste:fg=#C3C8CC,bg=#3A414A")

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#E3888C'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#E7CDFF'
FAST_HIGHLIGHT_STYLES[alias]='fg=#51B8AA'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#51B8AA'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#51B8AA'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#51B8AA'
FAST_HIGHLIGHT_STYLES[function]='fg=#5CC1B3'
FAST_HIGHLIGHT_STYLES[command]='fg=#51B8AA'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#E7CDFF'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#E7CDFF'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#9AA4AE'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#51B8AA'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#A2A9AF,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#A2A9AF,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#9AA4AE,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#A2A9AF,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#A2A9AF,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#C294E6'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#C294E6'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#C294E6'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#9AA4AE'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#5EC4B5'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#5EC4B5'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#5EC4B5'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#E3888C,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#E3888C,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#E3888C,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#C294E6'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#C294E6'
FAST_HIGHLIGHT_STYLES[assign]='fg=#C3C8CC'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#5EC4B5'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#C294E6'
FAST_HIGHLIGHT_STYLES[comment]='fg=#9AA4AE,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#A2A9AF'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#A2A9AF'
FAST_HIGHLIGHT_STYLES[variable]='fg=#C294E6'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#C3C8CC'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#E7CDFF'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#C294E6'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#9AA4AE'
FAST_HIGHLIGHT_STYLES[exec-descriptor]='fg=#E7CDFF'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#E7CDFF'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#C294E6'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#51B8AA'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#C294E6'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#E3888C'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#5EC4B5'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#E7CDFF'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#51B8AA'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#51B8AA'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#5EC4B5'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#E7CDFF'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#62C7B9'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#51B8AA'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#51B8AA'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#E7CDFF'
FAST_HIGHLIGHT_STYLES[optarg-string]='fg=#5EC4B5'
FAST_HIGHLIGHT_STYLES[optarg-number]='fg=#C294E6'
FAST_HIGHLIGHT_STYLES[recursive-base]='none'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#51B8AA'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#E3888C'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#5EC4B5'
FAST_HIGHLIGHT_STYLES[subtle-bg]='bg=#4A402E'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#535D68'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;81;184;170:ln=38;2;194;148;230:or=38;2;227;136;140:mi=9;38;2;227;136;140:so=38;2;94;196;181:pi=38;2;197;161;90:ex=38;2;92;193;179:bd=38;2;98;199;185:cd=38;2;98;199;185:su=1;38;2;227;136;140:sg=1;38;2;197;161;90:tw=1;38;2;94;196;181:ow=4;38;2;81;184;170:st=1;38;2;81;184;170'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;58;65;74;38;2;195;200;204"
zstyle ':completion:*:descriptions' format '%F{#9AA4AE}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#9AA4AE}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#E3888C}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#C3C8CC,bg:#272C33,hl:#5CC1B3' \
  '--color=fg+:#C3C8CC,bg+:#3A414A,hl+:#5CC1B3' \
  '--color=border:#858F9B,header:#51B8AA,gutter:#272C33' \
  '--color=spinner:#E7CDFF,info:#9AA4AE' \
  '--color=pointer:#5CC1B3,marker:#5EC4B5,prompt:#5CC1B3'
zstyle ':fzf-tab:*' default-color $'\033[38;2;195;200;204m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;81;184;170m' $'\033[38;2;94;196;181m' $'\033[38;2;231;205;255m' $'\033[38;2;194;148;230m' $'\033[38;2;98;199;185m' $'\033[38;2;92;193;179m' $'\033[38;2;197;161;90m' $'\033[38;2;227;136;140m'

# Prompt helpers
export TOKEN_FG='#C3C8CC'
export TOKEN_BG='#272C33'
export TOKEN_ACCENT='#5CC1B3'
export TOKEN_ACCENT2='#E7CDFF'
export TOKEN_BLUE='#51B8AA'
export TOKEN_GREEN='#5EC4B5'
export TOKEN_RED='#E3888C'
export TOKEN_YELLOW='#C5A15A'
export TOKEN_PURPLE='#C294E6'
export TOKEN_CYAN='#62C7B9'
export TOKEN_MUTED='#9AA4AE'
