# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token-flint dark colors.

# ZLE selection and pasted text
zle_highlight=(${zle_highlight:#region:*})
zle_highlight=(${zle_highlight:#paste:*} "region:fg=#DCE1E6,bg=#3A414A" "paste:fg=#DCE1E6,bg=#3A414A")

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#D47A7F'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#73B7B0'
FAST_HIGHLIGHT_STYLES[alias]='fg=#82AAD0'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#82AAD0'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#82AAD0'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#82AAD0'
FAST_HIGHLIGHT_STYLES[function]='fg=#B7A0E0'
FAST_HIGHLIGHT_STYLES[command]='fg=#82AAD0'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#73B7B0'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#73B7B0'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#929BA5'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#82AAD0'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#C2C9D0,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#C2C9D0,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#929BA5,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#C2C9D0,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#C2C9D0,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#B7A0E0'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#B7A0E0'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#B7A0E0'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#929BA5'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#8FB583'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#8FB583'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#8FB583'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#D47A7F,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#D47A7F,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#D47A7F,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#B7A0E0'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#B7A0E0'
FAST_HIGHLIGHT_STYLES[assign]='fg=#DCE1E6'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#8FB583'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#B7A0E0'
FAST_HIGHLIGHT_STYLES[comment]='fg=#929BA5,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#C2C9D0'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#C2C9D0'
FAST_HIGHLIGHT_STYLES[variable]='fg=#B7A0E0'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#DCE1E6'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#73B7B0'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#B7A0E0'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#929BA5'
FAST_HIGHLIGHT_STYLES[exec-descriptor]='fg=#73B7B0'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#73B7B0'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#B7A0E0'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#82AAD0'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#B7A0E0'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#D47A7F'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#8FB583'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#73B7B0'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#82AAD0'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#82AAD0'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#8FB583'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#73B7B0'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#73B7B0'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#82AAD0'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#82AAD0'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#73B7B0'
FAST_HIGHLIGHT_STYLES[optarg-string]='fg=#8FB583'
FAST_HIGHLIGHT_STYLES[optarg-number]='fg=#B7A0E0'
FAST_HIGHLIGHT_STYLES[recursive-base]='none'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#82AAD0'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#D47A7F'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#8FB583'
FAST_HIGHLIGHT_STYLES[subtle-bg]='bg=#4A402E'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#59636E'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;130;170;208:ln=38;2;183;160;224:or=38;2;212;122;127:mi=9;38;2;212;122;127:so=38;2;143;181;131:pi=38;2;198;161;90:ex=38;2;183;160;224:bd=38;2;115;183;176:cd=38;2;115;183;176:su=1;38;2;212;122;127:sg=1;38;2;198;161;90:tw=1;38;2;143;181;131:ow=4;38;2;130;170;208:st=1;38;2;130;170;208'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;58;65;74;38;2;220;225;230"
zstyle ':completion:*:descriptions' format '%F{#929BA5}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#929BA5}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#D47A7F}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#DCE1E6,bg:#272C33,hl:#B7A0E0' \
  '--color=fg+:#DCE1E6,bg+:#3A414A,hl+:#B7A0E0' \
  '--color=border:#626C77,header:#82AAD0,gutter:#272C33' \
  '--color=spinner:#73B7B0,info:#929BA5' \
  '--color=pointer:#B7A0E0,marker:#8FB583,prompt:#B7A0E0'
zstyle ':fzf-tab:*' default-color $'\033[38;2;220;225;230m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;130;170;208m' $'\033[38;2;143;181;131m' $'\033[38;2;115;183;176m' $'\033[38;2;183;160;224m' $'\033[38;2;115;183;176m' $'\033[38;2;183;160;224m' $'\033[38;2;198;161;90m' $'\033[38;2;212;122;127m'

# Prompt helpers
export TOKEN_FG='#DCE1E6'
export TOKEN_BG='#272C33'
export TOKEN_ACCENT='#B7A0E0'
export TOKEN_ACCENT2='#73B7B0'
export TOKEN_BLUE='#82AAD0'
export TOKEN_GREEN='#8FB583'
export TOKEN_RED='#D47A7F'
export TOKEN_YELLOW='#C6A15A'
export TOKEN_PURPLE='#B7A0E0'
export TOKEN_CYAN='#73B7B0'
export TOKEN_MUTED='#929BA5'
