# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token-ultra light colors.

# ZLE selection and pasted text
zle_highlight=(${zle_highlight:#region:*})
zle_highlight=(${zle_highlight:#paste:*} "region:fg=#292a24,bg=#dedbd3" "paste:fg=#292a24,bg=#dedbd3")

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#aa4e55'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#87601b'
FAST_HIGHLIGHT_STYLES[alias]='fg=#536f88'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#536f88'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#536f88'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#536f88'
FAST_HIGHLIGHT_STYLES[function]='fg=#a44e31'
FAST_HIGHLIGHT_STYLES[command]='fg=#536f88'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#87601b'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#87601b'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#6d675f'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#536f88'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#3d3929,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#3d3929,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#6d675f,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#3d3929,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#3d3929,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#6d675f'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#4f714b'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#4f714b'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#4f714b'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#aa4e55,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#aa4e55,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#aa4e55,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[assign]='fg=#292a24'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#4f714b'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[comment]='fg=#6d675f,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#3d3929'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#3d3929'
FAST_HIGHLIGHT_STYLES[variable]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#292a24'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#87601b'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#6d675f'
FAST_HIGHLIGHT_STYLES[exec-descriptor]='fg=#87601b'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#87601b'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#536f88'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#aa4e55'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#4f714b'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#87601b'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#536f88'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#536f88'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#4f714b'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#87601b'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#2d6c6c'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#536f88'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#536f88'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#87601b'
FAST_HIGHLIGHT_STYLES[optarg-string]='fg=#4f714b'
FAST_HIGHLIGHT_STYLES[optarg-number]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[recursive-base]='none'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#536f88'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#aa4e55'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#4f714b'
FAST_HIGHLIGHT_STYLES[subtle-bg]='bg=#eadab6'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#b5b2ab'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;83;111;136:ln=38;2;124;97;154:or=38;2;170;78;85:mi=9;38;2;170;78;85:so=38;2;79;113;75:pi=38;2;131;95;16:ex=38;2;164;78;49:bd=38;2;45;108;108:cd=38;2;45;108;108:su=1;38;2;170;78;85:sg=1;38;2;131;95;16:tw=1;38;2;79;113;75:ow=4;38;2;83;111;136:st=1;38;2;83;111;136'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;222;219;211;38;2;41;42;36"
zstyle ':completion:*:descriptions' format '%F{#6d675f}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#6d675f}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#aa4e55}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#292a24,bg:#fbf9f4,hl:#a44e31' \
  '--color=fg+:#292a24,bg+:#dedbd3,hl+:#a44e31' \
  '--color=border:#888177,header:#536f88,gutter:#fbf9f4' \
  '--color=spinner:#87601b,info:#6d675f' \
  '--color=pointer:#a44e31,marker:#4f714b,prompt:#a44e31'
zstyle ':fzf-tab:*' default-color $'\033[38;2;41;42;36m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;83;111;136m' $'\033[38;2;79;113;75m' $'\033[38;2;135;96;27m' $'\033[38;2;124;97;154m' $'\033[38;2;45;108;108m' $'\033[38;2;164;78;49m' $'\033[38;2;131;95;16m' $'\033[38;2;170;78;85m'

# Prompt helpers
export TOKEN_FG='#292a24'
export TOKEN_BG='#fbf9f4'
export TOKEN_ACCENT='#a44e31'
export TOKEN_ACCENT2='#87601b'
export TOKEN_BLUE='#536f88'
export TOKEN_GREEN='#4f714b'
export TOKEN_RED='#aa4e55'
export TOKEN_YELLOW='#835f10'
export TOKEN_PURPLE='#7c619a'
export TOKEN_CYAN='#2d6c6c'
export TOKEN_MUTED='#6d675f'
