# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token-flint dark colors.

# ZLE selection and pasted text
zle_highlight=(${zle_highlight:#region:*})
zle_highlight=(${zle_highlight:#paste:*} "region:fg=#C3C8CC,bg=#3A414A" "paste:fg=#C3C8CC,bg=#3A414A")

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#E3888C'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#F8D28A'
FAST_HIGHLIGHT_STYLES[alias]='fg=#88ACC4'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#88ACC4'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#88ACC4'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#88ACC4'
FAST_HIGHLIGHT_STYLES[function]='fg=#EB9E83'
FAST_HIGHLIGHT_STYLES[command]='fg=#88ACC4'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#F8D28A'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#F8D28A'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#9AA4AE'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#88ACC4'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#A2A9AF,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#A2A9AF,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#9AA4AE,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#A2A9AF,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#A2A9AF,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#E09478'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#E09478'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#E09478'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#9AA4AE'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#A9B98C'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#A9B98C'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#A9B98C'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#E3888C,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#E3888C,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#E3888C,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#E09478'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#E09478'
FAST_HIGHLIGHT_STYLES[assign]='fg=#C3C8CC'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#A9B98C'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#E09478'
FAST_HIGHLIGHT_STYLES[comment]='fg=#9AA4AE,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#A2A9AF'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#A2A9AF'
FAST_HIGHLIGHT_STYLES[variable]='fg=#E09478'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#C3C8CC'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#F8D28A'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#E09478'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#9AA4AE'
FAST_HIGHLIGHT_STYLES[exec-descriptor]='fg=#F8D28A'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#F8D28A'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#E09478'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#88ACC4'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#E09478'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#E3888C'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#A9B98C'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#F8D28A'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#88ACC4'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#88ACC4'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#A9B98C'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#F8D28A'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#98BBD4'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#88ACC4'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#88ACC4'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#F8D28A'
FAST_HIGHLIGHT_STYLES[optarg-string]='fg=#A9B98C'
FAST_HIGHLIGHT_STYLES[optarg-number]='fg=#E09478'
FAST_HIGHLIGHT_STYLES[recursive-base]='none'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#88ACC4'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#E3888C'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#A9B98C'
FAST_HIGHLIGHT_STYLES[subtle-bg]='bg=#4A402E'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#535D68'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;136;172;196:ln=38;2;224;148;120:or=38;2;227;136;140:mi=9;38;2;227;136;140:so=38;2;169;185;140:pi=38;2;197;161;90:ex=38;2;235;158;131:bd=38;2;152;187;212:cd=38;2;152;187;212:su=1;38;2;227;136;140:sg=1;38;2;197;161;90:tw=1;38;2;169;185;140:ow=4;38;2;136;172;196:st=1;38;2;136;172;196'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;58;65;74;38;2;195;200;204"
zstyle ':completion:*:descriptions' format '%F{#9AA4AE}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#9AA4AE}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#E3888C}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#C3C8CC,bg:#272C33,hl:#EB9E83' \
  '--color=fg+:#C3C8CC,bg+:#3A414A,hl+:#EB9E83' \
  '--color=border:#858F9B,header:#88ACC4,gutter:#272C33' \
  '--color=spinner:#F8D28A,info:#9AA4AE' \
  '--color=pointer:#EB9E83,marker:#A9B98C,prompt:#EB9E83'
zstyle ':fzf-tab:*' default-color $'\033[38;2;195;200;204m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;136;172;196m' $'\033[38;2;169;185;140m' $'\033[38;2;248;210;138m' $'\033[38;2;224;148;120m' $'\033[38;2;152;187;212m' $'\033[38;2;235;158;131m' $'\033[38;2;197;161;90m' $'\033[38;2;227;136;140m'

# Prompt helpers
export TOKEN_FG='#C3C8CC'
export TOKEN_BG='#272C33'
export TOKEN_ACCENT='#EB9E83'
export TOKEN_ACCENT2='#F8D28A'
export TOKEN_BLUE='#88ACC4'
export TOKEN_GREEN='#A9B98C'
export TOKEN_RED='#E3888C'
export TOKEN_YELLOW='#C5A15A'
export TOKEN_PURPLE='#E09478'
export TOKEN_CYAN='#98BBD4'
export TOKEN_MUTED='#9AA4AE'
