# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token-flint light colors.

# ZLE selection and pasted text
zle_highlight=(${zle_highlight:#region:*})
zle_highlight=(${zle_highlight:#paste:*} "region:fg=#28313A,bg=#DCE2E7" "paste:fg=#28313A,bg=#DCE2E7")

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#BE3E50'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#946409'
FAST_HIGHLIGHT_STYLES[alias]='fg=#34779D'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#34779D'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#34779D'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#34779D'
FAST_HIGHLIGHT_STYLES[function]='fg=#B64E2E'
FAST_HIGHLIGHT_STYLES[command]='fg=#34779D'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#946409'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#946409'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#65717D'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#34779D'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#3D4853,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#3D4853,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#65717D,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#3D4853,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#3D4853,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#B64E2E'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#B64E2E'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#B64E2E'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#65717D'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#5A772B'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#5A772B'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#5A772B'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#BE3E50,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#BE3E50,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#BE3E50,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#B64E2E'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#B64E2E'
FAST_HIGHLIGHT_STYLES[assign]='fg=#28313A'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#5A772B'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#B64E2E'
FAST_HIGHLIGHT_STYLES[comment]='fg=#65717D,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#3D4853'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#3D4853'
FAST_HIGHLIGHT_STYLES[variable]='fg=#B64E2E'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#28313A'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#946409'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#B64E2E'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#65717D'
FAST_HIGHLIGHT_STYLES[exec-descriptor]='fg=#946409'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#946409'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#B64E2E'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#34779D'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#B64E2E'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#BE3E50'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#5A772B'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#946409'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#34779D'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#34779D'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#5A772B'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#946409'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#34779D'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#34779D'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#34779D'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#946409'
FAST_HIGHLIGHT_STYLES[optarg-string]='fg=#5A772B'
FAST_HIGHLIGHT_STYLES[optarg-number]='fg=#B64E2E'
FAST_HIGHLIGHT_STYLES[recursive-base]='none'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#34779D'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#BE3E50'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#5A772B'
FAST_HIGHLIGHT_STYLES[subtle-bg]='bg=#E9DDBE'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#A3ADB6'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;52;119;157:ln=38;2;182;78;46:or=38;2;190;62;80:mi=9;38;2;190;62;80:so=38;2;90;119;43:pi=38;2;148;100;9:ex=38;2;182;78;46:bd=38;2;52;119;157:cd=38;2;52;119;157:su=1;38;2;190;62;80:sg=1;38;2;148;100;9:tw=1;38;2;90;119;43:ow=4;38;2;52;119;157:st=1;38;2;52;119;157'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;220;226;231;38;2;40;49;58"
zstyle ':completion:*:descriptions' format '%F{#65717D}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#65717D}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#BE3E50}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#28313A,bg:#F5F7F8,hl:#B64E2E' \
  '--color=fg+:#28313A,bg+:#DCE2E7,hl+:#B64E2E' \
  '--color=border:#828E9A,header:#34779D,gutter:#F5F7F8' \
  '--color=spinner:#946409,info:#65717D' \
  '--color=pointer:#B64E2E,marker:#5A772B,prompt:#B64E2E'
zstyle ':fzf-tab:*' default-color $'\033[38;2;40;49;58m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;52;119;157m' $'\033[38;2;90;119;43m' $'\033[38;2;148;100;9m' $'\033[38;2;182;78;46m' $'\033[38;2;52;119;157m' $'\033[38;2;182;78;46m' $'\033[38;2;148;100;9m' $'\033[38;2;190;62;80m'

# Prompt helpers
export TOKEN_FG='#28313A'
export TOKEN_BG='#F5F7F8'
export TOKEN_ACCENT='#B64E2E'
export TOKEN_ACCENT2='#946409'
export TOKEN_BLUE='#34779D'
export TOKEN_GREEN='#5A772B'
export TOKEN_RED='#BE3E50'
export TOKEN_YELLOW='#946409'
export TOKEN_PURPLE='#B64E2E'
export TOKEN_CYAN='#34779D'
export TOKEN_MUTED='#65717D'
