# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token-ultra dark colors.

# ZLE selection and pasted text
zle_highlight=(${zle_highlight:#region:*})
zle_highlight=(${zle_highlight:#paste:*} "region:fg=#c5c1b8,bg=#3c3b36" "paste:fg=#c5c1b8,bg=#3c3b36")

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#dd8384'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#f7c988'
FAST_HIGHLIGHT_STYLES[alias]='fg=#8aa5bb'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#8aa5bb'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#8aa5bb'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#8aa5bb'
FAST_HIGHLIGHT_STYLES[function]='fg=#ed9574'
FAST_HIGHLIGHT_STYLES[command]='fg=#8aa5bb'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#f7c988'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#f7c988'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#a39d94'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#8aa5bb'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#a7a299,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#a7a299,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#a39d94,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#a7a299,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#a7a299,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#b296cb'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#b296cb'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#b296cb'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#a39d94'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#9ab58e'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#9ab58e'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#9ab58e'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#dd8384,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#dd8384,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#dd8384,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#b296cb'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#b296cb'
FAST_HIGHLIGHT_STYLES[assign]='fg=#c5c1b8'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#9ab58e'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#b296cb'
FAST_HIGHLIGHT_STYLES[comment]='fg=#a39d94,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#a7a299'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#a7a299'
FAST_HIGHLIGHT_STYLES[variable]='fg=#b296cb'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#c5c1b8'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#f7c988'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#b296cb'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#a39d94'
FAST_HIGHLIGHT_STYLES[exec-descriptor]='fg=#f7c988'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#f7c988'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#b296cb'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#8aa5bb'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#b296cb'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#dd8384'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#9ab58e'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#f7c988'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#8aa5bb'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#8aa5bb'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#9ab58e'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#f7c988'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#7ebcbb'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#8aa5bb'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#8aa5bb'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#f7c988'
FAST_HIGHLIGHT_STYLES[optarg-string]='fg=#9ab58e'
FAST_HIGHLIGHT_STYLES[optarg-number]='fg=#b296cb'
FAST_HIGHLIGHT_STYLES[recursive-base]='none'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#8aa5bb'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#dd8384'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#9ab58e'
FAST_HIGHLIGHT_STYLES[subtle-bg]='bg=#4d4231'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#585855'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;138;165;187:ln=38;2;178;150;203:or=38;2;221;131;132:mi=9;38;2;221;131;132:so=38;2;154;181;142:pi=38;2;191;156;83:ex=38;2;237;149;116:bd=38;2;126;188;187:cd=38;2;126;188;187:su=1;38;2;221;131;132:sg=1;38;2;191;156;83:tw=1;38;2;154;181;142:ow=4;38;2;138;165;187:st=1;38;2;138;165;187'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;60;59;54;38;2;197;193;184"
zstyle ':completion:*:descriptions' format '%F{#a39d94}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#a39d94}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#dd8384}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#c5c1b8,bg:#272724,hl:#ed9574' \
  '--color=fg+:#c5c1b8,bg+:#3c3b36,hl+:#ed9574' \
  '--color=border:#8d8983,header:#8aa5bb,gutter:#272724' \
  '--color=spinner:#f7c988,info:#a39d94' \
  '--color=pointer:#ed9574,marker:#9ab58e,prompt:#ed9574'
zstyle ':fzf-tab:*' default-color $'\033[38;2;197;193;184m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;138;165;187m' $'\033[38;2;154;181;142m' $'\033[38;2;247;201;136m' $'\033[38;2;178;150;203m' $'\033[38;2;126;188;187m' $'\033[38;2;237;149;116m' $'\033[38;2;191;156;83m' $'\033[38;2;221;131;132m'

# Prompt helpers
export TOKEN_FG='#c5c1b8'
export TOKEN_BG='#272724'
export TOKEN_ACCENT='#ed9574'
export TOKEN_ACCENT2='#f7c988'
export TOKEN_BLUE='#8aa5bb'
export TOKEN_GREEN='#9ab58e'
export TOKEN_RED='#dd8384'
export TOKEN_YELLOW='#bf9c53'
export TOKEN_PURPLE='#b296cb'
export TOKEN_CYAN='#7ebcbb'
export TOKEN_MUTED='#a39d94'
