# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token-temper dark colors.

# ZLE selection and pasted text
zle_highlight=(${zle_highlight:#region:*})
zle_highlight=(${zle_highlight:#paste:*} "region:fg=#DCE1E6,bg=#3A414A" "paste:fg=#DCE1E6,bg=#3A414A")

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#D47A7F'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[alias]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[function]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[command]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#929BA5'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#C2C9D0,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#C2C9D0,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#929BA5,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#C2C9D0,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#C2C9D0,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#929BA5'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#D47A7F,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#D47A7F,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#D47A7F,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[assign]='fg=#DCE1E6'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[comment]='fg=#929BA5,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#C2C9D0'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#C2C9D0'
FAST_HIGHLIGHT_STYLES[variable]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#DCE1E6'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#929BA5'
FAST_HIGHLIGHT_STYLES[exec-descriptor]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#D47A7F'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[optarg-string]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[optarg-number]='fg=#B184D5'
FAST_HIGHLIGHT_STYLES[recursive-base]='none'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#D47A7F'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#56BCAE'
FAST_HIGHLIGHT_STYLES[subtle-bg]='bg=#4A402E'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#59636E'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;86;188;174:ln=38;2;177;132;213:or=38;2;212;122;127:mi=9;38;2;212;122;127:so=38;2;86;188;174:pi=38;2;198;161;90:ex=38;2;86;188;174:bd=38;2;86;188;174:cd=38;2;86;188;174:su=1;38;2;212;122;127:sg=1;38;2;198;161;90:tw=1;38;2;86;188;174:ow=4;38;2;86;188;174:st=1;38;2;86;188;174'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;58;65;74;38;2;220;225;230"
zstyle ':completion:*:descriptions' format '%F{#929BA5}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#929BA5}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#D47A7F}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#DCE1E6,bg:#272C33,hl:#56BCAE' \
  '--color=fg+:#DCE1E6,bg+:#3A414A,hl+:#56BCAE' \
  '--color=border:#626C77,header:#56BCAE,gutter:#272C33' \
  '--color=spinner:#B184D5,info:#929BA5' \
  '--color=pointer:#56BCAE,marker:#56BCAE,prompt:#56BCAE'
zstyle ':fzf-tab:*' default-color $'\033[38;2;220;225;230m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;86;188;174m' $'\033[38;2;86;188;174m' $'\033[38;2;177;132;213m' $'\033[38;2;177;132;213m' $'\033[38;2;86;188;174m' $'\033[38;2;86;188;174m' $'\033[38;2;198;161;90m' $'\033[38;2;212;122;127m'

# Prompt helpers
export TOKEN_FG='#DCE1E6'
export TOKEN_BG='#272C33'
export TOKEN_ACCENT='#56BCAE'
export TOKEN_ACCENT2='#B184D5'
export TOKEN_BLUE='#56BCAE'
export TOKEN_GREEN='#56BCAE'
export TOKEN_RED='#D47A7F'
export TOKEN_YELLOW='#C6A15A'
export TOKEN_PURPLE='#B184D5'
export TOKEN_CYAN='#56BCAE'
export TOKEN_MUTED='#929BA5'
