# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token-flint light colors.

# ZLE selection and pasted text
zle_highlight=(${zle_highlight:#region:*})
zle_highlight=(${zle_highlight:#paste:*} "region:fg=#283039,bg=#DCE2E7" "paste:fg=#283039,bg=#DCE2E7")

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#BF3F50'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#6b4600'
FAST_HIGHLIGHT_STYLES[alias]='fg=#035378'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#035378'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#035378'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#035378'
FAST_HIGHLIGHT_STYLES[function]='fg=#902A03'
FAST_HIGHLIGHT_STYLES[command]='fg=#035378'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#6b4600'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#6b4600'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#414C57'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#035378'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#46515D,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#46515D,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#414C57,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#46515D,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#46515D,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#852500'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#852500'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#852500'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#414C57'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#3D5902'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#3D5902'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#3D5902'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#BF3F50,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#BF3F50,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#BF3F50,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#852500'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#852500'
FAST_HIGHLIGHT_STYLES[assign]='fg=#283039'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#3D5902'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#852500'
FAST_HIGHLIGHT_STYLES[comment]='fg=#414C57,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#46515D'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#46515D'
FAST_HIGHLIGHT_STYLES[variable]='fg=#852500'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#283039'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#6b4600'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#852500'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#414C57'
FAST_HIGHLIGHT_STYLES[exec-descriptor]='fg=#6b4600'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#6b4600'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#852500'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#035378'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#852500'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#BF3F50'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#3D5902'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#6b4600'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#035378'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#035378'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#3D5902'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#6b4600'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#09567B'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#035378'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#035378'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#6b4600'
FAST_HIGHLIGHT_STYLES[optarg-string]='fg=#3D5902'
FAST_HIGHLIGHT_STYLES[optarg-number]='fg=#852500'
FAST_HIGHLIGHT_STYLES[recursive-base]='none'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#035378'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#BF3F50'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#3D5902'
FAST_HIGHLIGHT_STYLES[subtle-bg]='bg=#E9DDBE'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#A7B2BB'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;3;83;120:ln=38;2;133;37;0:or=38;2;191;63;80:mi=9;38;2;191;63;80:so=38;2;61;89;2:pi=38;2;153;105;20:ex=38;2;144;42;3:bd=38;2;9;86;123:cd=38;2;9;86;123:su=1;38;2;191;63;80:sg=1;38;2;153;105;20:tw=1;38;2;61;89;2:ow=4;38;2;3;83;120:st=1;38;2;3;83;120'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;220;226;231;38;2;40;48;57"
zstyle ':completion:*:descriptions' format '%F{#414C57}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#414C57}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#BF3F50}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#283039,bg:#F5F7F8,hl:#902A03' \
  '--color=fg+:#283039,bg+:#DCE2E7,hl+:#902A03' \
  '--color=border:#444E59,header:#035378,gutter:#F5F7F8' \
  '--color=spinner:#6b4600,info:#414C57' \
  '--color=pointer:#902A03,marker:#3D5902,prompt:#902A03'
zstyle ':fzf-tab:*' default-color $'\033[38;2;40;48;57m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;3;83;120m' $'\033[38;2;61;89;2m' $'\033[38;2;107;70;0m' $'\033[38;2;133;37;0m' $'\033[38;2;9;86;123m' $'\033[38;2;144;42;3m' $'\033[38;2;153;105;20m' $'\033[38;2;191;63;80m'

# Prompt helpers
export TOKEN_FG='#283039'
export TOKEN_BG='#F5F7F8'
export TOKEN_ACCENT='#902A03'
export TOKEN_ACCENT2='#6b4600'
export TOKEN_BLUE='#035378'
export TOKEN_GREEN='#3D5902'
export TOKEN_RED='#BF3F50'
export TOKEN_YELLOW='#996914'
export TOKEN_PURPLE='#852500'
export TOKEN_CYAN='#09567B'
export TOKEN_MUTED='#414C57'
