# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token-ultra light colors.

# ZLE selection and pasted text
zle_highlight=(${zle_highlight:#region:*})
zle_highlight=(${zle_highlight:#paste:*} "region:fg=#31312b,bg=#dedbd3" "paste:fg=#31312b,bg=#dedbd3")

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#ae5158'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#6c4800'
FAST_HIGHLIGHT_STYLES[alias]='fg=#37526a'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#37526a'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#37526a'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#37526a'
FAST_HIGHLIGHT_STYLES[function]='fg=#893517'
FAST_HIGHLIGHT_STYLES[command]='fg=#37526a'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#6c4800'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#6c4800'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#514b44'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#37526a'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#565141,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#565141,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#514b44,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#565141,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#565141,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#514b44'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#385a35'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#385a35'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#385a35'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#ae5158,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#ae5158,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#ae5158,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[assign]='fg=#31312b'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#385a35'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[comment]='fg=#514b44,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#565141'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#565141'
FAST_HIGHLIGHT_STYLES[variable]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#31312b'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#6c4800'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#514b44'
FAST_HIGHLIGHT_STYLES[exec-descriptor]='fg=#6c4800'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#6c4800'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#37526a'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#ae5158'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#385a35'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#6c4800'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#37526a'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#37526a'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#385a35'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#6c4800'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#185b5b'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#37526a'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#37526a'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#6c4800'
FAST_HIGHLIGHT_STYLES[optarg-string]='fg=#385a35'
FAST_HIGHLIGHT_STYLES[optarg-number]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[recursive-base]='none'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#37526a'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#ae5158'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#385a35'
FAST_HIGHLIGHT_STYLES[subtle-bg]='bg=#eadab6'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#b5b2ab'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;55;82;106:ln=38;2;87;60;114:or=38;2;174;81;88:mi=9;38;2;174;81;88:so=38;2;56;90;53:pi=38;2;146;110;37:ex=38;2;137;53;23:bd=38;2;24;91;91:cd=38;2;24;91;91:su=1;38;2;174;81;88:sg=1;38;2;146;110;37:tw=1;38;2;56;90;53:ow=4;38;2;55;82;106:st=1;38;2;55;82;106'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;222;219;211;38;2;49;49;43"
zstyle ':completion:*:descriptions' format '%F{#514b44}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#514b44}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#ae5158}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#31312b,bg:#fbf9f4,hl:#893517' \
  '--color=fg+:#31312b,bg+:#dedbd3,hl+:#893517' \
  '--color=border:#544e44,header:#37526a,gutter:#fbf9f4' \
  '--color=spinner:#6c4800,info:#514b44' \
  '--color=pointer:#893517,marker:#385a35,prompt:#893517'
zstyle ':fzf-tab:*' default-color $'\033[38;2;49;49;43m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;55;82;106m' $'\033[38;2;56;90;53m' $'\033[38;2;108;72;0m' $'\033[38;2;87;60;114m' $'\033[38;2;24;91;91m' $'\033[38;2;137;53;23m' $'\033[38;2;146;110;37m' $'\033[38;2;174;81;88m'

# Prompt helpers
export TOKEN_FG='#31312b'
export TOKEN_BG='#fbf9f4'
export TOKEN_ACCENT='#893517'
export TOKEN_ACCENT2='#6c4800'
export TOKEN_BLUE='#37526a'
export TOKEN_GREEN='#385a35'
export TOKEN_RED='#ae5158'
export TOKEN_YELLOW='#926e25'
export TOKEN_PURPLE='#573c72'
export TOKEN_CYAN='#185b5b'
export TOKEN_MUTED='#514b44'
