# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token-meridian dark colors.

# ZLE selection and pasted text
zle_highlight=(${zle_highlight:#region:*})
zle_highlight=(${zle_highlight:#paste:*} "region:fg=#c9c0b1,bg=#3c3b36" "paste:fg=#c9c0b1,bg=#3c3b36")

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#db8935'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#f8c88f'
FAST_HIGHLIGHT_STYLES[alias]='fg=#66abc6'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#66abc6'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#66abc6'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#66abc6'
FAST_HIGHLIGHT_STYLES[function]='fg=#e89a49'
FAST_HIGHLIGHT_STYLES[command]='fg=#66abc6'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#f8c88f'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#f8c88f'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#a69c91'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#66abc6'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#aba195,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#aba195,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#a69c91,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#aba195,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#aba195,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#b991db'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#b991db'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#b991db'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#a69c91'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#8cbb62'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#8cbb62'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#8cbb62'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#db8935,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#db8935,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#db8935,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#b991db'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#b991db'
FAST_HIGHLIGHT_STYLES[assign]='fg=#c9c0b1'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#8cbb62'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#b991db'
FAST_HIGHLIGHT_STYLES[comment]='fg=#a69c91,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#aba195'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#aba195'
FAST_HIGHLIGHT_STYLES[variable]='fg=#b991db'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#c9c0b1'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#f8c88f'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#b991db'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#a69c91'
FAST_HIGHLIGHT_STYLES[exec-descriptor]='fg=#f8c88f'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#f8c88f'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#b991db'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#66abc6'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#b991db'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#db8935'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#8cbb62'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#f8c88f'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#66abc6'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#66abc6'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#8cbb62'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#f8c88f'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#d9a86e'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#66abc6'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#66abc6'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#f8c88f'
FAST_HIGHLIGHT_STYLES[optarg-string]='fg=#8cbb62'
FAST_HIGHLIGHT_STYLES[optarg-number]='fg=#b991db'
FAST_HIGHLIGHT_STYLES[recursive-base]='none'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#66abc6'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#db8935'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#8cbb62'
FAST_HIGHLIGHT_STYLES[subtle-bg]='bg=#4d4231'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#585855'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;102;171;198:ln=38;2;185;145;219:or=38;2;219;137;53:mi=9;38;2;219;137;53:so=38;2;140;187;98:pi=38;2;217;145;72:ex=38;2;232;154;73:bd=38;2;217;168;110:cd=38;2;217;168;110:su=1;38;2;219;137;53:sg=1;38;2;217;145;72:tw=1;38;2;140;187;98:ow=4;38;2;102;171;198:st=1;38;2;102;171;198'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;60;59;54;38;2;201;192;177"
zstyle ':completion:*:descriptions' format '%F{#a69c91}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#a69c91}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#db8935}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#c9c0b1,bg:#272724,hl:#e89a49' \
  '--color=fg+:#c9c0b1,bg+:#3c3b36,hl+:#e89a49' \
  '--color=border:#91887d,header:#66abc6,gutter:#272724' \
  '--color=spinner:#f8c88f,info:#a69c91' \
  '--color=pointer:#e89a49,marker:#8cbb62,prompt:#e89a49'
zstyle ':fzf-tab:*' default-color $'\033[38;2;201;192;177m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;102;171;198m' $'\033[38;2;140;187;98m' $'\033[38;2;248;200;143m' $'\033[38;2;185;145;219m' $'\033[38;2;217;168;110m' $'\033[38;2;232;154;73m' $'\033[38;2;217;145;72m' $'\033[38;2;219;137;53m'

# Prompt helpers
export TOKEN_FG='#c9c0b1'
export TOKEN_BG='#272724'
export TOKEN_ACCENT='#e89a49'
export TOKEN_ACCENT2='#f8c88f'
export TOKEN_BLUE='#66abc6'
export TOKEN_GREEN='#8cbb62'
export TOKEN_RED='#db8935'
export TOKEN_YELLOW='#d99148'
export TOKEN_PURPLE='#b991db'
export TOKEN_CYAN='#d9a86e'
export TOKEN_MUTED='#a69c91'
