// Generated by token colorscheme. Do not edit manually.

t.prefs_.set('color-palette-overrides', [
  '#1d1d1c',
  '#c67777',
  '#7da47a',
  '#c4a855',
  '#7b9ebd',
  '#a68bbf',
  '#6ba8a8',
  '#d4cfc6',
  '#5a5955',
  '#d97757',
  '#98bf95',
  '#c4956a',
  '#96b8d3',
  '#bea5d4',
  '#88c0c0',
  '#e8e4dc',
]);
t.prefs_.set('foreground-color', '#e8e4dc');
t.prefs_.set('background-color', '#262624');
t.prefs_.set('cursor-color', 'rgba(232, 228, 220, 0.5)');
