// Generated by token colorscheme. Do not edit manually.

t.prefs_.set('color-palette-overrides', [
  '#323128',
  '#ad5253',
  '#365a33',
  '#857238',
  '#315270',
  '#573c72',
  '#185b5b',
  '#b4b2ab',
  '#504b44',
  '#863716',
  '#274b24',
  '#6d4717',
  '#335471',
  '#6b5488',
  '#387272',
  '#faf9f5',
]);
t.prefs_.set('foreground-color', '#323128');
t.prefs_.set('background-color', '#faf9f5');
t.prefs_.set('cursor-color', 'rgba(50, 49, 40, 0.5)');
