// Generated by token colorscheme. Do not edit manually.

t.prefs_.set('color-palette-overrides', [
  '#1d1d1c',
  '#d68585',
  '#8fb78c',
  '#b99d4a',
  '#81a5c4',
  '#b195ca',
  '#7dbbba',
  '#a6a198',
  '#8a8884',
  '#f4906f',
  '#a0c89d',
  '#f7c699',
  '#8fb1cb',
  '#bea5d4',
  '#88c0c0',
  '#c3c0b8',
]);
t.prefs_.set('foreground-color', '#c3c0b8');
t.prefs_.set('background-color', '#262624');
t.prefs_.set('cursor-color', 'rgba(195, 192, 184, 0.5)');
