// Generated by token colorscheme. Do not edit manually.

t.prefs_.set('color-palette-overrides', [
  '#2a2920',
  '#b05555',
  '#3f643c',
  '#6e5c20',
  '#527594',
  '#7c619a',
  '#2d6c6c',
  '#b5b2ab',
  '#6c675f',
  '#9a4929',
  '#3a5e37',
  '#876032',
  '#486a88',
  '#6f578c',
  '#286363',
  '#faf9f5',
]);
t.prefs_.set('foreground-color', '#2a2920');
t.prefs_.set('background-color', '#faf9f5');
t.prefs_.set('cursor-color', 'rgba(42, 41, 32, 0.5)');
